export interface AnimalFrequencyData {
  id: string;
  name: string;
  hindiName: string;
  category: 'large_mammal' | 'small_mammal' | 'primate' | 'bird' | 'reptile' | 'rodent' | 'wild_pig';
  frequencyRange: { min: number; max: number };
  optimalFrequency: number;
  effectiveness: 'high' | 'medium' | 'low';
  habitat: string;
  cropDamageType: string;
  activeTime: 'day' | 'night' | 'both';
  seasonalPeak: string[];
}

export const animalCategories = {
  large_mammal: { label: 'Large Mammals', icon: '🐘', color: 'bg-amber-500' },
  small_mammal: { label: 'Small Mammals', icon: '🦔', color: 'bg-orange-500' },
  primate: { label: 'Primates (Monkeys)', icon: '🐒', color: 'bg-yellow-500' },
  bird: { label: 'Birds', icon: '🦅', color: 'bg-sky-500' },
  reptile: { label: 'Reptiles', icon: '🐍', color: 'bg-green-500' },
  rodent: { label: 'Rodents', icon: '🐀', color: 'bg-gray-500' },
  wild_pig: { label: 'Wild Pigs', icon: '🐗', color: 'bg-rose-500' },
};

export const indianWildlifeFrequencies: AnimalFrequencyData[] = [
  // LARGE MAMMALS
  {
    id: 'elephant',
    name: 'Indian Elephant',
    hindiName: 'हाथी (Haathi)',
    category: 'large_mammal',
    frequencyRange: { min: 14, max: 24 },
    optimalFrequency: 18,
    effectiveness: 'medium',
    habitat: 'Forests of Karnataka, Kerala, Assam, West Bengal',
    cropDamageType: 'Trampling, eating crops (sugarcane, banana, paddy)',
    activeTime: 'both',
    seasonalPeak: ['Oct', 'Nov', 'Dec'],
  },
  {
    id: 'nilgai',
    name: 'Nilgai (Blue Bull)',
    hindiName: 'नीलगाय (Neelgaay)',
    category: 'large_mammal',
    frequencyRange: { min: 18, max: 28 },
    optimalFrequency: 22,
    effectiveness: 'high',
    habitat: 'Rajasthan, Gujarat, Maharashtra, MP, UP',
    cropDamageType: 'Grazing on wheat, mustard, vegetables',
    activeTime: 'both',
    seasonalPeak: ['Nov', 'Dec', 'Jan', 'Feb'],
  },
  {
    id: 'sambar_deer',
    name: 'Sambar Deer',
    hindiName: 'सांभर (Saambhar)',
    category: 'large_mammal',
    frequencyRange: { min: 20, max: 30 },
    optimalFrequency: 25,
    effectiveness: 'high',
    habitat: 'Western Ghats, Central India forests',
    cropDamageType: 'Grazing on crops, young shoots',
    activeTime: 'night',
    seasonalPeak: ['Oct', 'Nov', 'Mar', 'Apr'],
  },
  {
    id: 'spotted_deer',
    name: 'Spotted Deer (Chital)',
    hindiName: 'चीतल (Cheetal)',
    category: 'large_mammal',
    frequencyRange: { min: 22, max: 32 },
    optimalFrequency: 27,
    effectiveness: 'high',
    habitat: 'Throughout India in forests',
    cropDamageType: 'Grazing on agricultural fields',
    activeTime: 'both',
    seasonalPeak: ['Nov', 'Dec', 'Jan'],
  },
  {
    id: 'blackbuck',
    name: 'Blackbuck',
    hindiName: 'काला हिरण (Kala Hiran)',
    category: 'large_mammal',
    frequencyRange: { min: 20, max: 28 },
    optimalFrequency: 24,
    effectiveness: 'high',
    habitat: 'Rajasthan, Gujarat, MP, Maharashtra grasslands',
    cropDamageType: 'Wheat, gram, vegetables',
    activeTime: 'day',
    seasonalPeak: ['Nov', 'Dec', 'Jan', 'Feb'],
  },
  {
    id: 'gaur',
    name: 'Indian Gaur (Bison)',
    hindiName: 'गौर (Gaur)',
    category: 'large_mammal',
    frequencyRange: { min: 16, max: 24 },
    optimalFrequency: 20,
    effectiveness: 'medium',
    habitat: 'Western Ghats, Northeast India',
    cropDamageType: 'Paddy, sugarcane, vegetables',
    activeTime: 'both',
    seasonalPeak: ['Oct', 'Nov', 'Dec'],
  },

  // WILD PIGS
  {
    id: 'wild_boar',
    name: 'Wild Boar',
    hindiName: 'जंगली सूअर (Jangli Suar)',
    category: 'wild_pig',
    frequencyRange: { min: 15, max: 25 },
    optimalFrequency: 20,
    effectiveness: 'high',
    habitat: 'Throughout India',
    cropDamageType: 'Rooting, eating tubers, sugarcane, maize, groundnut',
    activeTime: 'night',
    seasonalPeak: ['Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
  },
  {
    id: 'feral_pig',
    name: 'Feral Pig',
    hindiName: 'आवारा सूअर (Awara Suar)',
    category: 'wild_pig',
    frequencyRange: { min: 15, max: 25 },
    optimalFrequency: 20,
    effectiveness: 'high',
    habitat: 'Near villages across India',
    cropDamageType: 'Root vegetables, paddy, maize',
    activeTime: 'night',
    seasonalPeak: ['Year-round'],
  },

  // PRIMATES
  {
    id: 'rhesus_macaque',
    name: 'Rhesus Macaque',
    hindiName: 'बंदर (Bandar)',
    category: 'primate',
    frequencyRange: { min: 16, max: 22 },
    optimalFrequency: 18,
    effectiveness: 'medium',
    habitat: 'Throughout North and Central India',
    cropDamageType: 'Fruits, vegetables, grains - very destructive',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'bonnet_macaque',
    name: 'Bonnet Macaque',
    hindiName: 'टोपी बंदर (Topi Bandar)',
    category: 'primate',
    frequencyRange: { min: 16, max: 22 },
    optimalFrequency: 19,
    effectiveness: 'medium',
    habitat: 'South India (Karnataka, Tamil Nadu, Kerala)',
    cropDamageType: 'Coconuts, bananas, fruits',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'langur',
    name: 'Hanuman Langur',
    hindiName: 'लंगूर (Langoor)',
    category: 'primate',
    frequencyRange: { min: 17, max: 23 },
    optimalFrequency: 20,
    effectiveness: 'medium',
    habitat: 'Throughout India forests and villages',
    cropDamageType: 'Fruits, vegetables, leaves',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },

  // RODENTS
  {
    id: 'indian_porcupine',
    name: 'Indian Porcupine',
    hindiName: 'साही (Saahi)',
    category: 'rodent',
    frequencyRange: { min: 18, max: 25 },
    optimalFrequency: 22,
    effectiveness: 'high',
    habitat: 'Throughout India in burrows',
    cropDamageType: 'Root vegetables, tubers, groundnut',
    activeTime: 'night',
    seasonalPeak: ['Oct', 'Nov', 'Dec', 'Jan'],
  },
  {
    id: 'bandicoot_rat',
    name: 'Greater Bandicoot Rat',
    hindiName: 'पिग रैट (Pig Rat)',
    category: 'rodent',
    frequencyRange: { min: 20, max: 30 },
    optimalFrequency: 25,
    effectiveness: 'high',
    habitat: 'Agricultural fields across India',
    cropDamageType: 'Grains, vegetables, stored crops',
    activeTime: 'night',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'field_rat',
    name: 'Indian Field Rat',
    hindiName: 'खेत का चूहा (Khet ka Chuha)',
    category: 'rodent',
    frequencyRange: { min: 22, max: 32 },
    optimalFrequency: 27,
    effectiveness: 'high',
    habitat: 'Agricultural fields throughout India',
    cropDamageType: 'Paddy, wheat, sugarcane, vegetables',
    activeTime: 'night',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'soft_furred_rat',
    name: 'Soft-furred Field Rat',
    hindiName: 'मुलायम चूहा (Mulayam Chuha)',
    category: 'rodent',
    frequencyRange: { min: 22, max: 32 },
    optimalFrequency: 26,
    effectiveness: 'high',
    habitat: 'Crop fields, grasslands',
    cropDamageType: 'Grains, pulses',
    activeTime: 'night',
    seasonalPeak: ['Oct', 'Nov', 'Dec'],
  },
  {
    id: 'palm_squirrel',
    name: 'Indian Palm Squirrel',
    hindiName: 'गिलहरी (Gilhari)',
    category: 'rodent',
    frequencyRange: { min: 20, max: 28 },
    optimalFrequency: 24,
    effectiveness: 'medium',
    habitat: 'Throughout India',
    cropDamageType: 'Fruits, nuts, seeds',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },

  // BIRDS
  {
    id: 'peacock',
    name: 'Indian Peafowl',
    hindiName: 'मोर (Mor)',
    category: 'bird',
    frequencyRange: { min: 2, max: 5 },
    optimalFrequency: 3,
    effectiveness: 'low',
    habitat: 'Throughout India',
    cropDamageType: 'Seeds, grains, vegetables (protected species)',
    activeTime: 'day',
    seasonalPeak: ['Mar', 'Apr', 'May', 'Jun'],
  },
  {
    id: 'parakeet',
    name: 'Rose-ringed Parakeet',
    hindiName: 'तोता (Tota)',
    category: 'bird',
    frequencyRange: { min: 2, max: 4 },
    optimalFrequency: 3,
    effectiveness: 'medium',
    habitat: 'Throughout India',
    cropDamageType: 'Fruits (guava, mango, pomegranate), sunflower',
    activeTime: 'day',
    seasonalPeak: ['Mar', 'Apr', 'May', 'Jun'],
  },
  {
    id: 'house_crow',
    name: 'House Crow',
    hindiName: 'कौआ (Kauwa)',
    category: 'bird',
    frequencyRange: { min: 3, max: 6 },
    optimalFrequency: 4,
    effectiveness: 'high',
    habitat: 'Throughout India',
    cropDamageType: 'Seeds, fruits, newly sown fields',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'jungle_crow',
    name: 'Large-billed Crow',
    hindiName: 'जंगली कौआ (Jangli Kauwa)',
    category: 'bird',
    frequencyRange: { min: 3, max: 6 },
    optimalFrequency: 4,
    effectiveness: 'high',
    habitat: 'Throughout India',
    cropDamageType: 'Fruits, maize, sorghum',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'house_sparrow',
    name: 'House Sparrow',
    hindiName: 'गौरैया (Gauraiya)',
    category: 'bird',
    frequencyRange: { min: 4, max: 8 },
    optimalFrequency: 6,
    effectiveness: 'medium',
    habitat: 'Throughout India near habitation',
    cropDamageType: 'Grains, rice, wheat',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'baya_weaver',
    name: 'Baya Weaver',
    hindiName: 'बया (Baya)',
    category: 'bird',
    frequencyRange: { min: 4, max: 8 },
    optimalFrequency: 6,
    effectiveness: 'high',
    habitat: 'Grasslands and agricultural areas',
    cropDamageType: 'Rice, wheat, jowar',
    activeTime: 'day',
    seasonalPeak: ['Jun', 'Jul', 'Aug', 'Sep'],
  },
  {
    id: 'mynah',
    name: 'Common Myna',
    hindiName: 'मैना (Maina)',
    category: 'bird',
    frequencyRange: { min: 3, max: 6 },
    optimalFrequency: 5,
    effectiveness: 'medium',
    habitat: 'Throughout India',
    cropDamageType: 'Fruits, grains',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'pigeon',
    name: 'Rock Pigeon',
    hindiName: 'कबूतर (Kabutar)',
    category: 'bird',
    frequencyRange: { min: 4, max: 7 },
    optimalFrequency: 5,
    effectiveness: 'high',
    habitat: 'Throughout India',
    cropDamageType: 'Grains, pulses, seeds',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'spotted_dove',
    name: 'Spotted Dove',
    hindiName: 'फाख्ता (Faakhta)',
    category: 'bird',
    frequencyRange: { min: 4, max: 7 },
    optimalFrequency: 5,
    effectiveness: 'high',
    habitat: 'Throughout India',
    cropDamageType: 'Seeds, grains',
    activeTime: 'day',
    seasonalPeak: ['Year-round'],
  },

  // SMALL MAMMALS
  {
    id: 'indian_hare',
    name: 'Indian Hare',
    hindiName: 'खरगोश (Khargosh)',
    category: 'small_mammal',
    frequencyRange: { min: 18, max: 25 },
    optimalFrequency: 22,
    effectiveness: 'high',
    habitat: 'Throughout India in grasslands',
    cropDamageType: 'Vegetables, pulses, young shoots',
    activeTime: 'night',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'jackal',
    name: 'Indian Jackal',
    hindiName: 'सियार (Siyaar)',
    category: 'small_mammal',
    frequencyRange: { min: 16, max: 22 },
    optimalFrequency: 19,
    effectiveness: 'high',
    habitat: 'Throughout India',
    cropDamageType: 'Melons, sugarcane, fruits',
    activeTime: 'night',
    seasonalPeak: ['Apr', 'May', 'Jun'],
  },
  {
    id: 'jungle_cat',
    name: 'Jungle Cat',
    hindiName: 'जंगली बिल्ली (Jangli Billi)',
    category: 'small_mammal',
    frequencyRange: { min: 18, max: 24 },
    optimalFrequency: 21,
    effectiveness: 'medium',
    habitat: 'Throughout India in scrublands',
    cropDamageType: 'Poultry (indirect crop protection)',
    activeTime: 'night',
    seasonalPeak: ['Year-round'],
  },
  {
    id: 'palm_civet',
    name: 'Asian Palm Civet',
    hindiName: 'खटास (Khataas)',
    category: 'small_mammal',
    frequencyRange: { min: 18, max: 25 },
    optimalFrequency: 22,
    effectiveness: 'medium',
    habitat: 'Western Ghats, Northeast India',
    cropDamageType: 'Coffee berries, fruits',
    activeTime: 'night',
    seasonalPeak: ['Oct', 'Nov', 'Dec'],
  },

  // REPTILES
  {
    id: 'monitor_lizard',
    name: 'Bengal Monitor',
    hindiName: 'गोह (Goh)',
    category: 'reptile',
    frequencyRange: { min: 100, max: 500 },
    optimalFrequency: 300,
    effectiveness: 'low',
    habitat: 'Throughout India',
    cropDamageType: 'Eggs (poultry), sometimes beneficial for pest control',
    activeTime: 'day',
    seasonalPeak: ['Mar', 'Apr', 'May'],
  },
  {
    id: 'cobra',
    name: 'Indian Cobra',
    hindiName: 'नाग (Naag)',
    category: 'reptile',
    frequencyRange: { min: 200, max: 600 },
    optimalFrequency: 400,
    effectiveness: 'low',
    habitat: 'Throughout India',
    cropDamageType: 'Danger to farmers (beneficial for rodent control)',
    activeTime: 'both',
    seasonalPeak: ['Jun', 'Jul', 'Aug', 'Sep'],
  },
  {
    id: 'rat_snake',
    name: 'Indian Rat Snake',
    hindiName: 'धामिन (Dhaamin)',
    category: 'reptile',
    frequencyRange: { min: 200, max: 600 },
    optimalFrequency: 400,
    effectiveness: 'low',
    habitat: 'Throughout India',
    cropDamageType: 'Beneficial - eats rodents',
    activeTime: 'day',
    seasonalPeak: ['Mar', 'Apr', 'May'],
  },
];

export const frequencyBands = [
  { 
    name: 'Infrasonic (Very Low)',
    range: '0-20 Hz',
    min: 0, max: 20,
    targetAnimals: ['Elephants', 'Large mammals'],
    notes: 'Felt as vibration, good for elephants'
  },
  { 
    name: 'Low Frequency',
    range: '20-100 Hz',
    min: 20, max: 100,
    targetAnimals: ['Reptiles', 'Large snakes'],
    notes: 'Ground vibrations effective'
  },
  { 
    name: 'Medium-Low Frequency',
    range: '100-500 Hz',
    min: 100, max: 500,
    targetAnimals: ['Snakes', 'Monitor lizards'],
    notes: 'Reptile deterrent range'
  },
  { 
    name: 'Medium Frequency (Audio)',
    range: '500 Hz - 5 kHz',
    min: 500, max: 5000,
    targetAnimals: ['Birds', 'Crows', 'Parakeets'],
    notes: 'Most effective for birds'
  },
  { 
    name: 'High Frequency',
    range: '5-15 kHz',
    min: 5000, max: 15000,
    targetAnimals: ['Monkeys', 'Dogs', 'Cats'],
    notes: 'Primates and canines'
  },
  { 
    name: 'Ultrasonic',
    range: '15-25 kHz',
    min: 15000, max: 25000,
    targetAnimals: ['Rodents', 'Rats', 'Mice', 'Bats'],
    notes: 'Best for rodent control'
  },
  { 
    name: 'High Ultrasonic',
    range: '25-45 kHz',
    min: 25000, max: 45000,
    targetAnimals: ['Insects', 'Small rodents'],
    notes: 'Insect and small pest deterrent'
  },
];

export function getRecommendedFrequency(animalIds: string[]): number {
  const animals = indianWildlifeFrequencies.filter(a => animalIds.includes(a.id));
  if (animals.length === 0) return 20;
  
  const avgOptimal = animals.reduce((sum, a) => sum + a.optimalFrequency, 0) / animals.length;
  return Math.round(avgOptimal);
}

export function getAnimalsByCategory(category: keyof typeof animalCategories): AnimalFrequencyData[] {
  return indianWildlifeFrequencies.filter(a => a.category === category);
}

export function getAnimalsByFrequencyRange(minHz: number, maxHz: number): AnimalFrequencyData[] {
  return indianWildlifeFrequencies.filter(a => 
    a.frequencyRange.min <= maxHz && a.frequencyRange.max >= minHz
  );
}
